// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg7LiJalkVZdDLZV_bB0NivtIlnWyOLmU',
    appId: '1:887002477759:web:4a30af45a4424902d0020a',
    messagingSenderId: '887002477759',
    projectId: 'campuseventflutter',
    authDomain: 'campuseventflutter.firebaseapp.com',
    storageBucket: 'campuseventflutter.firebasestorage.app',
    measurementId: 'G-0F012EVGGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIlR9DLnrrok3Hx_9T12r7J1yQjDm_tQM',
    appId: '1:887002477759:android:06db2f43033477cdd0020a',
    messagingSenderId: '887002477759',
    projectId: 'campuseventflutter',
    storageBucket: 'campuseventflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxNoQJk--u5njMyAlhYW3YKMj_ypH8iZA',
    appId: '1:887002477759:ios:463cf827d8f3bb62d0020a',
    messagingSenderId: '887002477759',
    projectId: 'campuseventflutter',
    storageBucket: 'campuseventflutter.firebasestorage.app',
    iosBundleId: 'com.example.campusEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxNoQJk--u5njMyAlhYW3YKMj_ypH8iZA',
    appId: '1:887002477759:ios:463cf827d8f3bb62d0020a',
    messagingSenderId: '887002477759',
    projectId: 'campuseventflutter',
    storageBucket: 'campuseventflutter.firebasestorage.app',
    iosBundleId: 'com.example.campusEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg7LiJalkVZdDLZV_bB0NivtIlnWyOLmU',
    appId: '1:887002477759:web:dd3241473dc0a2d7d0020a',
    messagingSenderId: '887002477759',
    projectId: 'campuseventflutter',
    authDomain: 'campuseventflutter.firebaseapp.com',
    storageBucket: 'campuseventflutter.firebasestorage.app',
    measurementId: 'G-5PF5NX5E2W',
  );

}